-- 코드를 입력하세요
SELECT 
	f.WAREHOUSE_ID, f.WAREHOUSE_NAME, f.ADDRESS
    , CASE 
    	WHEN FREEZER_YN IS NULL THEN 'N'
        ELSE FREEZER_YN
    	END as FREEZER_YN
    FROM FOOD_WAREHOUSE as f
    WHERE f.ADDRESS like '경기도%'
    ORDER BY f.WAREHOUSE_ID;